### PR TITLE
Add type hints to layer_integrated_gradients.py

### PR DESCRIPTION
**Pull request by quinton-hoole**
See also: https://github.com/pytorch/captum/pull/184

Tests:

captum] black .
reformatted /data/users/quinton/captum/captum/attr/_core/layer/layer_integrated_gradients.py
All done! ✨ 🍰 ✨
1 file reformatted, 105 files left unchanged.
captum] flake8 .
captum] ./scripts/run_mypy.sh
Success: no issues found in 43 source files
Success: no issues found in 48 source files

This is my first contribution to PyTorch, so I want to confirm that my dev process and initial attempt are sound.  More methods can be typehinted in this or followup PR's (similar to #184 above).

### CODE REVIEW

File: captum/attr/_core/layer/layer_integrated_gradients.py [hunk 1]
```diff
@@ -63,16 +70,22 @@ def __init__(self, forward_func, layer, device_ids=None):
...
+            Union[Tensor, int, float, Tuple[Union[Tensor, int, float], ...]]
+        ] = None,
+        target: Optional[
+            Union[int, Tuple[int, ...], Tensor, List[Tuple[int, ...]]]
+        ] = None,
+        additional_forward_args: Any = None,
+        n_steps: int = 50,
+        method: str = "gausslegendre",
+        internal_batch_size: Optional[int] = None,
+        return_convergence_delta: Optional[bool] = False,
```
Comment (vivekmig) [inline captum/attr/_core/layer/layer_integrated_gradients.py]: These two arguments (return_convergence_delta and attribute_to_layer_input) should just have a bool type, since they default to False, not None.

File: tests/attr/layer/test_layer_integrated_gradients.py [hunk 2]
```diff
@@ -126,7 +130,12 @@ def _assert_compare_with_emb_patching(self, input, baseline, additional_args):
         assertArraysAlmostEqual(delta, delta_with_ig)
 
     def _assert_compare_with_expected(
-        self, model, target_layer, test_input, expected_ig, additional_input=None,
+        self,
+        model: Module,
+        target_layer: Module,
+        test_input: Union[Tensor, Tuple[Tensor, ...]],
+        expected_ig: Tuple[List[List[float]], List[List[float]]],
```
Comment (vivekmig) [inline tests/attr/layer/test_layer_integrated_gradients.py]: nit: This is correct for the existing usage, but to make this more generic, could change this to Tuple[List[List[float]], ...], so we can also pass arbitrary length tuples in the future.

**Comment by vivekmig** [comment]
Hi @quinton-hoole , I have made some updates to the class hierarchy for Layer Integrated Gradients here https://github.com/pytorch/captum/pull/244, so please merge with these changes when you update this PR, thanks!

**Comment by quinton-hoole** [comment]
@vivekmig Awesome!  I was actually a bit stuck on some type hinting apparently related to attributes().  Hopefully this will help to resolve those.  Otherwise I will contact you shortly for some help.

**Comment by quinton-hoole** [comment]
@vivekmig Since merging your updates in #244 I'm getting the following error (I had zero errors before the merge).  Does not seem to be related to any of the changes I've made. Any advice?  I'll push the current state of my branch here for your reference.

**Comment by vivekmig** [comment]
> @vivekmig Since merging your updates in #244 I'm getting the following error (I had zero errors before the merge). Does not seem to be related to any of the changes I've made. Any advice? I'll push the current state of my branch here for your reference.
> 
> ```
> ./scripts/run_mypy.sh
> Success: no issues found in 44 source files
> tests/attr/neuron/test_neuron_gradient_shap.py:66: error: "Tensor" has no attribute "__iter__"; maybe "__ior__", "__int__", or "__invert__"? (not iterable)
> Found 1 error in 1 file (checked 48 source files)
> ```

This error is due to torch 1.3 missing some type hints for tensors, which was fixed here https://github.com/pytorch/pytorch/pull/28578. If you upgrade to torch 1.4, that should fix the issue!

**Comment by quinton-hoole** [comment]
> > @vivekmig Since merging your updates in #244 I'm getting the following error (I had zero errors before the merge). Does not seem to be related to any of the changes I've made. Any advice? I'll push the current state of my branch here for your reference.
> > ```
> > ./scripts/run_mypy.sh
> > Success: no issues found in 44 source files
> > tests/attr/neuron/test_neuron_gradient_shap.py:66: error: "Tensor" has no attribute "__iter__"; maybe "__ior__", "__int__", or "__invert__"? (not iterable)
> > Found 1 error in 1 file (checked 48 source files)
> > ```
> 
> This error is due to torch 1.3 missing some type hints for tensors, which was fixed here [pytorch/pytorch#28578](https://github.com/pytorch/pytorch/pull/28578). If you upgrade to torch 1.4, that should fix the issue!

Awesome!  Thanks.

**Comment by quinton-hoole** [comment]
@vivekmig I've pushed what will hopefully be the final commit.  mypy tests pass:

```
  ./scripts/run_mypy.sh
Success: no issues found in 44 source files
Success: no issues found in 48 source files
```

File: captum/attr/_core/layer/layer_integrated_gradients.py [hunk 3]
```diff
@@ -258,8 +271,12 @@ def attribute(
 
         # inputs -> these inputs are scaled
         def gradient_func(
-            forward_fn, inputs, target_ind=None, additional_forward_args=None
+            forward_fn: Callable,
+            inputs: Union[Tensor, Tuple[Tensor,...]],
+            target_ind: int = None,
+            additional_forward_args: Any = None
         ):
+            scattered_inputs: Union[Tuple[Union[Tensor, Tuple[Tensor, ...]]], Union[Tuple[Tensor, ...], List[Tuple[Any, ...]]]]
```
Comment (vivekmig) [inline captum/attr/_core/layer/layer_integrated_gradients.py]: I think we can avoid having this extra declaration, and instead just add "# type:ignore" to line 283 below with a short comment above on why this is necessary. This seems to be caused by the scatter method not having a precise enough return type in its stub, so let's just suppress the type warning there.

File: captum/attr/_core/layer/layer_integrated_gradients.py (hunk 1 above)
Comment (quinton-hoole) [reply captum/attr/_core/layer/layer_integrated_gradients.py]: Agreed, done.

File: tests/attr/layer/test_layer_integrated_gradients.py (hunk 2 above)
Comment (quinton-hoole) [reply tests/attr/layer/test_layer_integrated_gradients.py]: Agreed, done.

File: captum/attr/_core/layer/layer_integrated_gradients.py [hunk 4]
```diff
@@ -40,7 +42,12 @@ class LayerIntegratedGradients(LayerAttribution, GradientAttribution):
 
     """
 
-    def __init__(self, forward_func, layer, device_ids=None):
+    def __init__(
+        self,
+        forward_func: Callable,
+        layer: torch.nn.Module,
```
[the remark this answers is not in the document]
Comment (quinton-hoole) [reply captum/attr/_core/layer/layer_integrated_gradients.py]: Agreed, done.

File: captum/attr/_core/layer/layer_integrated_gradients.py [hunk 5]
```diff
@@ -258,8 +271,12 @@ def attribute(
 
         # inputs -> these inputs are scaled
         def gradient_func(
-            forward_fn, inputs, target_ind=None, additional_forward_args=None
+            forward_fn: Callable,
+            inputs: Union[Tensor, Tuple[Tensor,...]],
+            target_ind: int = None,
+            additional_forward_args: Any = None
```
[the remark this answers is not in the document]
Comment (quinton-hoole) [reply captum/attr/_core/layer/layer_integrated_gradients.py]: Agreed, done.

File: captum/attr/_core/layer/layer_integrated_gradients.py (hunk 3 above)
Comment (quinton-hoole) [reply captum/attr/_core/layer/layer_integrated_gradients.py]: Agreed, done.

**Comment by quinton-hoole** [comment]
Thanks @vivekmig.  I've addressed all the comments and rerun black and flake8.

File: captum/attr/_core/layer/layer_integrated_gradients.py [hunk 6]
```diff
@@ -258,12 +272,19 @@ def attribute(
 
         # inputs -> these inputs are scaled
         def gradient_func(
-            forward_fn, inputs, target_ind=None, additional_forward_args=None
-        ):
+            forward_fn: Callable,
+            inputs: Union[Tensor, Tuple[Tensor, ...]],
+            target_ind: int = None,
```
Comment (vivekmig) [inline captum/attr/_core/layer/layer_integrated_gradients.py]: This should actually be the same type as target above, (Optional[Union[int, Tuple[int, ...], Tensor, List[Tuple[int, ...]]]])

Comment (quinton-hoole) [reply captum/attr/_core/layer/layer_integrated_gradients.py]: Good catch!  Thanks, fixed.

**Comment by quinton-hoole** [comment]
> It seems like run_mypy is throwing an error now, the "type: ignore" needs to be moved to line 285, since the line was reformatted. Also, happened to notice that the targets hint also should be updated, if you can fix that as well and then rerun black, flake8, and run_mypy to double check everything that would be great! Thanks so much for your work on this, these should be the last changes!

Whoops!  My apologies for that oversight.  Fixed now.

**Comment by quinton-hoole** [comment]
@vivekmig I think this one is ready to merge now.

File: captum/attr/_core/layer/layer_integrated_gradients.py [hunk 7]
```diff
@@ -64,16 +72,22 @@ def __init__(self, forward_func, layer, device_ids=None):
...
+        ] = None,
+        target: Optional[
+            Union[int, Tuple[int, ...], Tensor, List[Tuple[int, ...]]]
+        ] = None,
+        additional_forward_args: Any = None,
+        n_steps: int = 50,
+        method: str = "gausslegendre",
+        internal_batch_size: Optional[int] = None,
+        return_convergence_delta: bool = False,
+        attribute_to_layer_input: bool = False,
```
Comment (NarineK) [inline captum/attr/_core/layer/layer_integrated_gradients.py]: Shouldn't this be optional too ? 
cc: @vivekmig

Comment (vivekmig) [reply captum/attr/_core/layer/layer_integrated_gradients.py]: I think this is fine the way it is, Optional[X] is equivalent to Union of X and None, in this case  attribute_to_layer_input will always take a bool value, even in the default case, and should never be None.
